Repository UMC-4th-Kosher-in-Korea/Kosher-in-Korea_Backend, pull requests merged in 2023-08, with the labels that each got.

#25 [feat] #24 주문 기능 장바구니 적용
  src/main/java/com/kusher/kusher_in_korea/auth/controller/UserController.java
  src/main/java/com/kusher/kusher_in_korea/auth/domain/User.java
  src/main/java/com/kusher/kusher_in_korea/auth/service/UserService.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/controller/OrdersController.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Cart.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/CartIngredient.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Ingredient.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Orders.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/OrdersIngredient.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/request/AddCartIngredientDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/request/CreateOrdersDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/request/RequestIngredientDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/response/CartDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/response/CartIngredientDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/response/DeliveryDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/response/IngredientDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/response/OrdersDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/response/OrdersIngredientDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/repository/CartIngredientRepository.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/repository/CartRepository.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/service/IngredientService.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/service/OrdersService.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/domain/Review.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/dto/CreateReviewDto.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/dto/ReviewDto.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/service/ReviewService.java
  src/main/java/com/kusher/kusher_in_korea/tabling/controller/RestaurantController.java
  src/main/java/com/kusher/kusher_in_korea/tabling/domain/Restaurant.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/CreateRestaurantDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/UpdateRestaurantDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/response/RestaurantDto.java
Labels: feat

#27 [feat] #26 식재료/평가 객체에 AWS S3로 이미지 추가
  build.gradle
  src/main/java/com/kusher/kusher_in_korea/KusherInKoreaApplication.java
  src/main/java/com/kusher/kusher_in_korea/image/config/S3Config.java
  src/main/java/com/kusher/kusher_in_korea/image/service/ImageUploadService.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/controller/IngredientController.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/request/CreateIngredientDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/service/IngredientService.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/controller/ReviewController.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/domain/Review.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/dto/CreateReviewDto.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/dto/ReviewDto.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/service/ReviewService.java
Labels: feat

#29 [fix] #28 API 관련 Dto & Entity 수정
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/domain/Feedback.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/dto/CreateFeedbackDto.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/service/FeedbackService.java
  src/main/java/com/kusher/kusher_in_korea/tabling/controller/ReservationController.java
  src/main/java/com/kusher/kusher_in_korea/tabling/controller/RestaurantController.java
  src/main/java/com/kusher/kusher_in_korea/tabling/domain/Reservation.java
  src/main/java/com/kusher/kusher_in_korea/tabling/domain/Restaurant.java
  src/main/java/com/kusher/kusher_in_korea/tabling/domain/RestaurantMenu.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/CreateReservationDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/CreateRestaurantDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/CreateRestaurantMenuDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/UpdateReservationDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/UpdateRestaurantDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/UpdateRestaurantMenuDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/response/ReservationDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/response/RestaurantDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/response/RestaurantMenuDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/service/ReservationService.java
  src/main/java/com/kusher/kusher_in_korea/tabling/service/RestaurantService.java
Labels: fix

#31 [refactor] #30 ApiResponse 객체 도입
  src/main/java/com/kusher/kusher_in_korea/auth/controller/UserController.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/controller/IngredientController.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/controller/OrdersController.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/controller/FeedbackController.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/controller/ReviewController.java
  src/main/java/com/kusher/kusher_in_korea/tabling/controller/ReservationController.java
  src/main/java/com/kusher/kusher_in_korea/tabling/controller/RestaurantController.java
  src/main/java/com/kusher/kusher_in_korea/util/api/ApiBody.java
  src/main/java/com/kusher/kusher_in_korea/util/api/ApiHeader.java
  src/main/java/com/kusher/kusher_in_korea/util/api/ApiResponse.java
  src/main/java/com/kusher/kusher_in_korea/util/exception/ResponseCode.java
Labels: refactor

#33 [feat] #19 결제 API 연동, 결제기능 구현
  .gitignore
  build.gradle
  src/main/java/com/kusher/kusher_in_korea/cash/controller/CashController.java
  src/main/java/com/kusher/kusher_in_korea/payment/Repository/PaymentRepository.java
  src/main/java/com/kusher/kusher_in_korea/payment/controller/PaymentController.java
  src/main/java/com/kusher/kusher_in_korea/payment/domain/Payment.java
  src/main/java/com/kusher/kusher_in_korea/payment/dto/PaymentDto.java
  src/main/java/com/kusher/kusher_in_korea/payment/payApiResponse.java
  src/main/java/com/kusher/kusher_in_korea/payment/service/PaymentService.java
  src/main/java/com/kusher/kusher_in_korea/util/exception/PaymentException.java
  src/main/java/com/kusher/kusher_in_korea/util/exception/ResponseCode.java
  src/main/resources/application.properties
Labels: feat

#35 [refactor] #32 식재료 조회 페이징 적용 및 예외처리 보강, Domain @Setter 제거
  src/main/java/com/kusher/kusher_in_korea/auth/domain/User.java
  src/main/java/com/kusher/kusher_in_korea/auth/service/UserService.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/controller/IngredientController.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/controller/OrdersController.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Address.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Cart.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/CartIngredient.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Category.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Delivery.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Ingredient.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Orders.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/OrdersIngredient.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/service/IngredientService.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/service/OrdersService.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/domain/Feedback.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/domain/Review.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/repository/ReviewRepository.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/service/ReviewService.java
  src/main/java/com/kusher/kusher_in_korea/tabling/domain/Reservation.java
  src/main/java/com/kusher/kusher_in_korea/tabling/domain/Restaurant.java
  src/main/java/com/kusher/kusher_in_korea/tabling/domain/RestaurantMenu.java
  src/main/java/com/kusher/kusher_in_korea/tabling/repository/RestaurantRepository.java
  src/main/java/com/kusher/kusher_in_korea/tabling/service/RestaurantService.java
  src/main/java/com/kusher/kusher_in_korea/util/exception/ResponseCode.java
Labels: refactor

#37 [fix] User Entity/API 수정
  src/main/java/com/kusher/kusher_in_korea/auth/controller/UserController.java
  src/main/java/com/kusher/kusher_in_korea/auth/domain/User.java
  src/main/java/com/kusher/kusher_in_korea/auth/dto/CreateUserDto.java
  src/main/java/com/kusher/kusher_in_korea/auth/dto/RequestUserDto.java
  src/main/java/com/kusher/kusher_in_korea/auth/dto/UpdateUserDto.java
  src/main/java/com/kusher/kusher_in_korea/auth/dto/UserDto.java
  src/main/java/com/kusher/kusher_in_korea/auth/repository/UserRepository.java
  src/main/java/com/kusher/kusher_in_korea/auth/service/UserService.java
Labels: fix

#39 [fix] #38 API 관련 예외처리 추가 및 일부 코드 수정
  src/main/java/com/kusher/kusher_in_korea/auth/domain/User.java
  src/main/java/com/kusher/kusher_in_korea/auth/dto/RequestUserDto.java
  src/main/java/com/kusher/kusher_in_korea/auth/service/UserService.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Cart.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/repository/CartRepository.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/service/IngredientService.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/service/OrdersService.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/service/FeedbackService.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/service/ReviewService.java
  src/main/java/com/kusher/kusher_in_korea/tabling/service/ReservationService.java
  src/main/java/com/kusher/kusher_in_korea/tabling/service/RestaurantService.java
  src/main/java/com/kusher/kusher_in_korea/util/api/ApiResponse.java
  src/main/java/com/kusher/kusher_in_korea/util/exception/GlobalExceptionHandler.java
Labels: fix

#41 [feat] #40 식당 메뉴에 사진 속성 추가
  src/main/java/com/kusher/kusher_in_korea/auth/controller/UserController.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/controller/IngredientController.java
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/controller/ReviewController.java
  src/main/java/com/kusher/kusher_in_korea/tabling/controller/RestaurantController.java
  src/main/java/com/kusher/kusher_in_korea/tabling/domain/Restaurant.java
  src/main/java/com/kusher/kusher_in_korea/tabling/domain/RestaurantMenu.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/CreateRestaurantMenuDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/response/RestaurantMenuDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/service/RestaurantService.java
Labels: feat

#44 [fix] #43 API 테스트 중 에러 수정
  src/main/java/com/kusher/kusher_in_korea/ingredient/controller/OrdersController.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/domain/Delivery.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/request/ChangeAddressDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/dto/request/CreateOrdersDto.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/service/OrdersService.java
  src/main/java/com/kusher/kusher_in_korea/tabling/domain/Reservation.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/CreateReservationDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/request/UpdateReservationDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/dto/response/ReservationDto.java
  src/main/java/com/kusher/kusher_in_korea/tabling/service/ReservationService.java
Labels: fix

#45 [fix] #43 피드백 생성 transactional 수정
  src/main/java/com/kusher/kusher_in_korea/reviewfeedback/service/FeedbackService.java
Labels: fix

#47 [fix] #46 클라이언트 요청사항 API에 반영
  src/main/java/com/kusher/kusher_in_korea/auth/controller/UserController.java
  src/main/java/com/kusher/kusher_in_korea/auth/domain/User.java
  src/main/java/com/kusher/kusher_in_korea/auth/dto/CreateUserDto.java
  src/main/java/com/kusher/kusher_in_korea/auth/dto/LoginDto.java
  src/main/java/com/kusher/kusher_in_korea/auth/dto/UpdateUserDto.java
  src/main/java/com/kusher/kusher_in_korea/auth/dto/UserDto.java
  src/main/java/com/kusher/kusher_in_korea/auth/service/UserService.java
Labels: fix

#48 [fix] #46 카테고리별 식재료조회 페이징 적용
  src/main/java/com/kusher/kusher_in_korea/ingredient/controller/IngredientController.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/repository/IngredientRepository.java
  src/main/java/com/kusher/kusher_in_korea/ingredient/service/IngredientService.java
Labels: fix

#49 [fix] #46 식재료추가 @RequestBody 삭제
  src/main/java/com/kusher/kusher_in_korea/tabling/controller/RestaurantController.java
Labels: fix
